/**
 * @file mqtt_driver.c
 * @brief 
 * 
 * 
 * 
*/

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"

#include "esp_log.h"
#include "esp_err.h"
#include "esp_event.h"
#include "esp_system.h"
#include "mqtt_client.h"

#include "cloud_mqtt.h"
#include "ota_update.h"

// Symbols generated by EMBED_TXTFILES in CMakeLists.txt
extern const uint8_t root_ca[]      asm("_binary_AmazonRootCA1_pem_start");
extern const uint8_t device_cert[]  asm("_binary_certificate_pem_crt_start");
extern const uint8_t private_key[]  asm("_binary_private_pem_key_start");

static const char *TAG = "MQTT";

// Event group used to signal MQTT connection status
EventGroupHandle_t mqtt_event_group;

esp_mqtt_client_handle_t client;

/**
 * @brief Event handler registered to receive MQTT events
 *
 *  This function is called by the MQTT client event loop.
 *
 * @param handler_args user data registered to the event.
 * @param base         Event base for the handler
 * @param event_id     The id for the received event.
 * @param event_data   The data for the event, esp_mqtt_event_handle_t.
*/
static void mqtt_event_handler(void *handler_args, 
                               esp_event_base_t event_base, 
                               int32_t event_id, 
                               void *event_data)
{
    esp_mqtt_event_handle_t event = event_data;

    switch(event->event_id) 
    {
        case MQTT_EVENT_CONNECTED:
            ESP_LOGI(TAG, "MQTT connected");
            xEventGroupSetBits(mqtt_event_group, MQTT_CONNECTED_BIT);
            break;
        case MQTT_EVENT_DISCONNECTED:
            ESP_LOGW(TAG, "MQTT disconnected");
            xEventGroupClearBits(mqtt_event_group, MQTT_CONNECTED_BIT);
            break;
        case MQTT_EVENT_DATA:
            // Check for Jobs topic
            if (strncmp(event->topic, JOBS_TOPIC_NOTIFY,      event->topic_len) == 0 ||
                strncmp(event->topic, JOBS_TOPIC_NOTIFY_NEXT, event->topic_len) == 0) 
                {
                    //Stroe the job document payload for OTA task
                    xSemaphoreTake(job_doc_mutex, portMAX_DELAY);
                    // .* to indicate the precision (%s depends on null-termination '\0')
                    snprintf(job_document, sizeof(job_document), "%.*s", event->data_len, event->data);
                    xSemaphoreGive(job_doc_mutex);

                    // Wake up the OTA task
                    xEventGroupSetBits(ota_event_group, JOB_NOTIFICATION_BIT);
                }
            break;
        default:
            break;
    }
}

/**
 * @brief 
 * 
 * 
*/
esp_err_t mqtt_init(void) 
{
    // Create the MQTT EventGroup
    mqtt_event_group = xEventGroupCreate();

    // Configure the AWS IoT Core parameters
    const esp_mqtt_client_config_t mqtt_config = 
    {
        .broker.address.uri              = AWS_ENDPOINT,            // AWS IoT Core endpoint URL (from AWS console)
        .broker.verification.certificate = (const char *)root_ca,   // AWS root certificate - verifies we're talking to real AWS 
        .credentials = {
            .client_id = clientID,                                  // Unique device ID on AWS IoT Core ("esp32_field_01")
            .authentication = {
                .certificate = (const char *)device_cert,           // Our device's certificate - proves our identity to AWS
                .key         = (const char *)private_key,           // Private key paired with device cert - never leaves the device
            },
        },
        .session.keepalive  = 120,          // Keepalive interval in seconds
        .network.timeout_ms = 10000,        // network timeout
        .buffer.size        = 1024,         // rx/tx buffer size
        .outbox.limit       = 4096,         // outbox size limit in bytes
    };

    client = esp_mqtt_client_init(&mqtt_config);
    if (client == NULL) {
        ESP_LOGE(TAG, "Failed to initialize MQTT client");
        return ESP_FAIL;
    }

    /**
     *  Register the mqtt_event_hanlder function with the event loop
     *  ESP_EVENT_ANY_ID - listens for any MQTT event (connect, disconnect, start etc)
    */
    esp_err_t ret = esp_mqtt_client_register_event(client, ESP_EVENT_ANY_ID, mqtt_event_handler, NULL);

    return ret;
}

esp_err_t mqtt_start(void) 
{
    esp_err_t ret;

    return ret = esp_mqtt_client_start(client);
}

esp_err_t mqtt_stop(void) 
{
    esp_err_t ret;

    return ret = esp_mqtt_client_stop(client);
}

/**
 * @brief Check if MQTT is currently connected
 * @return true if connected, false otherwise
*/
bool mqtt_is_connected(void)
{
    EventBits_t bits = xEventGroupGetBits(mqtt_event_group);
    return (bits & MQTT_CONNECTED_BIT) != 0;
}

/**
 * @brief Block the calling task until MQTT is connected
 * 
 * Used by other tasks to wait for mqtt to connect
*/
void mqtt_wait_until_connected(void)
{
    xEventGroupWaitBits(
        mqtt_event_group,
        MQTT_CONNECTED_BIT,
        pdFALSE,                  // Do not clear bit on exit  
        pdTRUE,                   // Wait for all bits (only one bit here)  
        portMAX_DELAY             // Wait indefinitely  
    );
}

/**
 * @brief Enqueue a message to the outbox to be published.
 * 
 * This is the non-blocking version of esp_mqtt_client_publish()
 * 
 * @ref code $(find $IDF_PATH -name "mqtt_client.h")
 * 
 * esp-mqtt manages the outbox internally. 
 *
 * @param topic   MQTT topic string to publish to (e.g. "sensor/data").
 * @param payload JSON string payload to publish.
 * @param len     Size of the epayload
 * @param qos     Quality of Service level (0 = at most once, 1 = at least once).
 *
 * @return ESP_OK on success, ESP_FAIL if not connected or publish fails.
*/
esp_err_t mqtt_publish_enqueue(const char *topic, const char *payload, size_t len, int qos, int retain, bool store) 
{
    if (!mqtt_is_connected()) {
        ESP_LOGW(TAG, "Publish skipped — MQTT not connected"); // Maybe prevent the queue to dequeueing here
        return ESP_FAIL;
    }

    int msg_id = esp_mqtt_client_enqueue(client, topic, payload, len, qos, retain, store);
    if (msg_id == -1) {
        ESP_LOGE(TAG, "Publish failed");
        return ESP_FAIL;
    }
    
    ESP_LOGI(TAG, "Published to [%s] msg_id=%d", topic, msg_id);
    return ESP_OK;
}

// Subscribe to a single topic
esp_err_t mqtt_subscribe_single(const char *topic, int qos)
{
    if (!mqtt_is_connected()) {
        ESP_LOGW(TAG, "Cannot subscribe — MQTT not connected");
        return ESP_FAIL;
    }

    int msg_id = esp_mqtt_client_subscribe(client, topic, qos);
    if (msg_id == -1) {
        ESP_LOGE(TAG, "Subscribe failed for [%s]", topic);
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "Subscribed to [%s] msg_id=%d", topic, msg_id);
    return ESP_OK;
}

// Subscribe to multiple topics
esp_err_t mqtt_subscribe_multiple(const esp_mqtt_topic_t *topic_list, size_t size)
{
    if (!mqtt_is_connected()) {
        ESP_LOGW(TAG, "Can not subscribe — MQTT not connected");
        return ESP_FAIL;
    }

    int msg_id = esp_mqtt_client_subscribe_multiple(client, topic_list, size);
    if (msg_id == -1) {
        ESP_LOGE(TAG, "Subscribe failed");
        return ESP_FAIL;
    }

    for (int i = 0; i < size; i++) {
        ESP_LOGI(TAG, "Subscribed to [%s] msg_id=%d", topic_list[i].filter, msg_id);
    }
    return ESP_OK;
}

