/**
 * @file mqtt_driver.c
 * @brief AWS IoT MQTT driver.
 * 
 * Handles connection lifecycle and raw publish to AWS IoT Core.
 * 
*/

#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "esp_log.h"
#include "esp_err.h"

#include "aws_iot_mqtt_client_interface.h"
#include "aws_iot_version.h"
#include "aws_iot_config.h"
#include "aws_iot_log.h"

#include "mqtt.h"

// Symbols generated by EMBED_TXTFILES in CMakeLists.txt
extern const uint8_t root_ca[]      asm("_binary_AmazonRootCA1_pem_start");
extern const uint8_t device_cert[]  asm("_binary_certificate_pem_crt_start");
extern const uint8_t private_key[]  asm("_binary_private_pem_key_start");

static const char *TAG = "MQTT";

// Event group used to signal MQTT connection status
EventGroupHandle_t mqtt_event_group;

static AWS_IoT_Client client;           // MQTT client handle

/**
 * @brief Event handler registered to receive MQTT events
 *
 *  This function is called by the MQTT client event loop.
 *
 * @param handler_args user data registered to the event.
 * @param base         Event base for the handler
 * @param event_id     The id for the received event.
 * @param event_data   The data for the event, esp_mqtt_event_handle_t.
*/
static void mqtt_event_handler(void *event_handler_args, 
                               esp_event_base_t event_base, 
                               int32_t event_id, 
                               void *event_data)
{
    switch(event_id) {
        case MQTT_EVENT_CONNECTED:
            ESP_LOGI(TAG, "MQTT connected");
            xEventGroupSetBits(mqtt_event_group, MQTT_CONNECTED_BIT);
            break;
        case MQTT_EVENT_DISCONNECTED:
            ESP_LOGW(TAG, "MQTT disconnected");
            xEventGroupClearBits(mqtt_event_group, MQTT_CONNECTED_BIT);
            break;
        default:
            break;
    }
}

/**
 * @brief Initialize and connect to AWS IoT Core over MQTT.
 *
 * Configures the MQTT client with TLS certificates and establishes
 * a connection to the AWS IoT endpoint.
 * 
 * Adapted from: ESP-IDF -> Framewroks -> AWS IoT 
 *               SIMS IOT Devices Youtube Channel
 *
 * @return ESP_OK on success, ESP_FAIL if init or connection fails.
 */
esp_err_t mqtt_init(void) 
{
    // Create the EventGroup
    mqtt_event_group = xEventGroupCreate();
    
    // Configure MQTT client
    AWS_IoT_Client_Init_Params params = iotClientInitParamsDefault;
    
    params.pHostURL                   = AWS_ENDPOINT;   // AWS IoT Core endpoint URL (from AWS console)
    params.port                       = 8883;           // Standard MQTT over TLS port
    params.pRootCALocation            = (const char *)root_ca;        // AWS root certificate - verifies we're talking to real AWS
    params.pDeviceCertLocation        = (const char *)device_cert;    // Our device's certificate - proves our identity to AWS
    params.pDevicePrivateKeyLocation  = (const char *)private_key;    // Private key paired with device cert - never leaves the device
    params.mqttCommandTimeout_ms      = 20000;          // How long to wait for MQTT operations (publish, subscribe) before failing
    params.tlsHandshakeTimeout_ms     = 10000;          // How long to wait for TLS handshake to complete before failing
    params.isSSLHostnameVerify        = true;           // Verify AWS endpoint hostname matches certificate (prevents MITM attacks)
    params.disconnectHandler          = NULL;           // Optional callback when connection drops - NULL for now
    params.clientID                   = clientID;       // Unique device ID on AWS IoT Core ("esp32_field_1")

    // Initialize AWS IoT
    IoT_Error_t rc = aws_iot_mqtt_init(&client, &params);
    if (rc != SUCCESS) {
        LOGE(TAG, "MQTT init error: %d", rc);
        return ESP_FAIL;
    }
    
    // Connect AWS IoT
    rc = aws_iot_mqtt_connect(&client, &params);
    if(rc != SUCCESS) {
        ESP_LOGE(TAG, "MQTT connect error: %d", rc);
        return ESP_FAIL;
    }
    
    ESP_LOGI(TAG, "Connected to AWS IoT Core");
    return ESP_OK;
}

/**
 * @brief Publish a message to an AWS IoT Core topic.
 *
 * @param topic   MQTT topic string to publish to (e.g. "sensor/data").
 * @param payload JSON string payload to publish.
 * @param qos     Quality of Service level (0 = at most once, 1 = at least once).
 *
 * @return ESP_OK on success, ESP_FAIL if not connected or publish fails.
*/
esp_err_t mqtt_publish(const char *topic, const char *payload, int qos) 
{
    if (!mqtt_is_connected()) {
        ESP_LOGW(TAG, "Publish skipped — not connected"); // Maybe prevent the queue to dequeueing here
        return ESP_FAIL;
    }

    IoT_Error_t rc = aws_iot_mqtt_publish(
        &client,
        topic, strlen(topic),
        (uint8_t *)payload, strlen(payload),
        qos, NULL, NULL
    );

    if (rc != SUCCESS) {
        ESP_LOGE(TAG, "Publish error: %d", rc);
        return ESP_FAIL;
    }

    return ESP_OK;
}

/**
 * @brief Check if MQTT is currently connected
 * @return true if connected, false otherwise
*/
bool mqtt_is_connected(void)
{
    EventBits_t bits = xEventGroupGetBits(mqtt_event_group);
    return (bits & MQTT_CONNECTED_BIT) != 0;
}